name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x' # Especifique a versão do .NET que você está usando

      - name: Restore dependencies
        run: dotnet restore Livraria.sln

      - name: Build
        run: dotnet build Livraria.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test tests/Livraria.Domain.Tests.csproj --configuration Release --no-build --verbosity normal

      - name: Run tests
        run: dotnet test tests/Livraria.Database.Tests.csproj --configuration Release --no-build --verbosity normal
